name: Run Cypress Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - name: Debug Secrets (Check if MONGODB_URI is set)
        run: echo "MONGODB_URI=${{ secrets.MONGODB_URI }}"

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build the Application
        run: npm run build

      - name: Start the Application in the Background
        run: npm start & # Run the application in the background

      - name: Wait for the server to start
        run: npx wait-on http://localhost:3001

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          wait-on: http://localhost:3001
          browser: chrome
          spec: "cypress/component-tests/**/*.cy.{js,jsx,ts,tsx}"
          project: "cypress"
          command: "cypress run --component"
